<?php
$_image = $this->getImage();
$image = $_image->getData();
$helper = Mage::helper('welance_kraken');

//unset not needed columns
unset($image['original_checksum']);
unset($image['checksum_after_upload']);
unset($image['success']);
unset($image['response_time']);

//convert sizes
$image['original_size'] = $helper->getImageSizeConverted($image['original_size']);
$image['size_after_upload'] = $helper->getImageSizeConverted($image['size_after_upload']);
$image['saved_file_size'] = $helper->getImageSizeConverted($image['saved_file_size']);

$header = array_keys($image);
$columns = array_values($image);

?>
<div class="content-header">
    <h3 class="icon-head head-images"><?php echo $this->__('View Image') ?></h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getBackButtonHtml() ?>
        <?php if($this->backupFileExists()): ?>
            <?php echo $this->getRestoreButtonHtml() ?>
        <?php endif; ?>
        <?php echo $this->getOptimizeButtonHtml() ?>
        <?php echo $this->getQueueButtonHtml() ?>
    </p>
</div>
<div class="grid">
    <table class="data-table" cellspacing="0">
        <thead>
            <tr class="headings">
                <th><?php echo $this->__('Image') ?></th>
                <?php foreach($header as $head): ?>
                    <th><?php echo $helper->mapTableHeader($head) ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td width="300">
                    <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$image['path'] . DS . $image['image_name'] ?>">
                        <img width="300" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$image['path'] . DS . $image['image_name'] ?>" alt="<?php echo $image['image_name'] ?>"/>
                    </a>
                </td>
                <?php foreach($columns as $column): ?>
                    <td><?php echo $column ?></td>
                <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
</div>